### ISSUE TITLE
Is this exclusive to Linux so you can promote it? Because that would be ironic

### ISSUE THREAD

**Issue by PPPDUD** [jdev082/SysInfTool#2]

**Comment by jdev082** [comment]
It isn't impossible to make it Linux and Windows but it's not easy either. However, if you wish to implement Windows support. I'll happily merge the PR!

(please test the PR, I don't have a Windows system at this time)

**Comment by PPPDUD** [comment]
> It isn't impossible to make it Linux and Windows but it's not easy either. However, if you wish to implement Windows support. I'll happily merge the PR!
> 
> (please test the PR, I don't have a Windows system at this time)

I've made the first step to Windows compatibility, removing the shebang.

**Comment by jdev082** [comment]
> > It isn't impossible to make it Linux and Windows but it's not easy either. However, if you wish to implement Windows support. I'll happily merge the PR!
> > (please test the PR, I don't have a Windows system at this time)
> 
> I've made the first step to Windows compatibility, removing the shebang.

Don't do this. This disallows it to be ran like a normal binary on Linux. It also doesn't affect Windows compatibility.
